b2_Taylor
elevoro/py111 pull request #12
Opened 2021-06-25 19:01 UTC by elevoro

2021-06-25 19:24 UTC, EnotYoyo requested changes
Эти задания расчитаны на оптимальный способ вычисления. Имея факториал 5 с предыдущего шага вычислять факторил 6 значительно проще: 5! (уже считали) * 6. 
Аналогично с числителем: зная x ** n, вычислить x**(n+1) можно значительно проще.

2021-07-05 08:10 UTC, EnotYoyo approved these changes
Принято. 

Удивительно, как две очень похожие функции имеют столь разные по названия переменные :)

2021-07-05 16:58 UTC, elevoro commented
> Принято.
> 
> Удивительно, как две очень похожие функции имеют столь разные по названия переменные :)

А что Вы имеете в виду, что удивительного? Если это намек, что я это где-то списала, то это не так, кусочки первоначального варианта кода да, смотрела в интернете, ну мне дома больше обратиться не к кому, кроме гугла в процессе решения. А внутреннюю функцию, которая считает текущий элемент, я намерено переименовала. Да, я понимаю, что это локальная функция и они могут называться одинаково.

2021-07-05 16:59 UTC, merged

2021-07-05 19:35 UTC, EnotYoyo commented
> > Принято.
> > Удивительно, как две очень похожие функции имеют столь разные по названия переменные :)
> 
> А что Вы имеете в виду, что удивительного? Если это намек, что я это где-то списала, то это не так, кусочки первоначального варианта кода да, смотрела в интернете, ну мне дома больше обратиться не к кому, кроме гугла в процессе решения. А внутреннюю функцию, которая считает текущий элемент, я намерено переименовала. Да, я понимаю, что это локальная функция и они могут называться одинаково.

Не, я это не имел ввиду :) 

Это скорее к тому, что имея одну написанную и работающую функцию, я бы ее скопировал и уже потом бы переделывал бы под новую формулу. Тем самым получив примерно одни названия переменных. 

А у Вас получилось, будто две совершенно разные функции, хотя они крайне похожи :)